# Generated by Django 3.2.5 on 2021-07-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_picture',
            new_name='picture_url',
        ),
    ]
